# Generated by Django 3.2 on 2021-05-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(db_index=True, max_length=15, verbose_name='账号')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=1)),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
