# Generated by Django 3.2 on 2021-05-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_question_catalogue_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_catalogue',
            name='sex',
        ),
    ]
