# Generated by Django 3.2 on 2021-05-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_question_catalogue_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_catalogue',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1),
        ),
    ]
