# Generated by Django 3.2 on 2021-05-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_question_catalogue_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=1000, null=True, verbose_name='答案'),
        ),
    ]
