# Generated by Django 3.2 on 2021-05-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solve_catalogue',
            name='password',
        ),
        migrations.RemoveField(
            model_name='solve_classify',
            name='password',
        ),
        migrations.RemoveField(
            model_name='solve_question',
            name='password',
        ),
    ]
